---
- hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache if needed.
      apt:
        update_cache: yes
        cache_valid_time: 86400
    - name: Ensure base packages are installed.
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - git
        - unzip
        - wget
  roles:
    - kamaln7.swapfile
    - git_config
    - apache2
    - mysql
    - T2L.php
    - T2L.composer
    - T2L.composer-global-packages
    - T2L.java
    - T2L.solr
  vars_files:
    - vars/swapfile.yml
    - vars/php.yml
    - vars/solr.yml
    - vars/composer.yml
    - vars/composer-global-packages.yml
