---
# This is exact copy of main playbook, except kamaln7.swapfile is skipped
# because it's not possible to test it on Travis CI. Also we manually add
# vagrant user as it does not exist in Docker.
- hosts: all
  remote_user: root

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 86400
    - name: Ensure base packages are installed
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - git
        - unzip
        - wget
    - name: Add vagrant user
      user:
        name: vagrant
        password: vagrant
        uid: 1000
  roles:
    - { role: kamaln7.swapfile, swapfile_size: false }
    - git_config
    - apache2
    - mysql
    - T2L.php
    - T2L.composer
    - T2L.composer-global-packages
    - T2L.java
    - T2L.solr
  vars_files:
    - vars/swapfile.yml
    - vars/php.yml
    - vars/solr.yml
    - vars/composer-global-packages.yml
